### ISSUE TITLE
کمبودهای ساحل در تقویم گوگل 

### ISSUE THREAD

**Issue by afshin-ir** [rastikerdar/sahel-font#27]
<div dir=rtl>
اگر فونت ساحل را بر تقویم تحت وب گوگل (Google Calendar) اِعمال کنیم، بعضی از آیکون‌ها درست دیده نمی‌شوند! 
مثلاً آیکون‌های ماه بعد، ماه قبل و جست‌وجو 

![image](https://user-images.githubusercontent.com/14938202/58859297-afa14200-86be-11e9-9782-35b929c9ead3.png)

**Comment by rastikerdar** [comment]
فکر می‌کنم شما فونت رو برای کل اِلمان‌های صفحه اعمال نموده‌اید در صورتی که احتمالا برخی از اون‌ها از یک فونت واحد یا از فونت متن استفاده نمی‌کنند. مثل موضوع آیکون‌فونت‌ها

**Comment by afshin-ir** [comment]
<div dir=rtl>
بله، همین کار را کردم. 
در واقع سؤالم هم همین بود که چگونه می‌شود در عین اِعمال این فونت بر کل صفحه آیکون‌فونت‌ها را هم درست نمایش داد؟

**Comment by rastikerdar** [comment]
این به نظر درست کار می‌کنه:  
```css
*:not([aria-hidden="true"]) {
    font-family: Sahel !important;
    letter-spacing: 0;
}
```

البته یک حالت این می‌تونه باشه. اما مشکل اینه که تراز آیکون‌ها متفاوته و کمی بالا و پایین ممکنه بشه:  
```css
* {
    font-family: Sahel, Material Icons Extended !important;
}
```
